version: "3.8"

services:
  stegocnn:
    build: 
      context: .
      dockerfile: Dockerfile
    container_name: stegocnn_dev
    env_file: .env
    volumes:
      - .:/app
      - ${DATASETS_PATH}:/app/data/datasets:ro
      - ${EXPERIMENT_OUTPUT_PATH}:/app/outputs
    working_dir: /app
    tty: true
    stdin_open: true
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: all
              capabilities: [gpu]