version: "3.8"

services:
  stegocnn:
    build: .
    container_name: stegocnn_container
    image: stego-project
    working_dir: /app
    volumes:
      - ./:/app
    # These two lines enable interactive use (e.g., a shell session or a Jupyter notebook)
    tty: true        
    stdin_open: true
    # This deploys the container with access to all available GPUs
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: all
              capabilities: [gpu]