version: "3.8"

services:
  stegocnn:
    build: .
    container_name: stegocnn_container
    image: stego-project
    working_dir: /app
    volumes:
      - ./:/app
    tty: true        
    stdin_open: true
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: all
              capabilities: [gpu]
